#!/bin/bash
if ! [ -x "$(command -v sass)" ]; then
  echo 'Error: sass is not installed.' >&2
  exit 1
fi

if ! [ -x "$(command -v postcss)" ]; then
  echo 'Error: postcss is not installed.' >&2
  exit 1
fi

if ! [ -x "$(command -v autoprefixer)" ]; then
  echo 'Error: autoprefixer is not installed.' >&2
  exit 1
fi

FILES=(sass_processed/style.css sass_processed/content-description.css sass_processed/table.css sass_processed/ranks.css sass_processed/course.css)

cd `dirname $0`

# Per-site theme overrides; generate the default when absent (gitignored)
if ! [ -f resources/_site_theme.scss ]; then
  printf '// Per-site SCSS overrides (gitignored; default generated by the build scripts).\n$theme_color: #9c3706;\n$nav_redesign: false;\n$accent_color: $theme_color;\n' > resources/_site_theme.scss
fi
# Upgrade older stubs that predate a variable (missing vars break the compile)
grep -q 'nav_redesign' resources/_site_theme.scss || printf '$nav_redesign: false;\n' >> resources/_site_theme.scss
grep -q 'accent_color' resources/_site_theme.scss || printf '$accent_color: $theme_color;\n' >> resources/_site_theme.scss

sass --silence-deprecation=import resources:sass_processed

echo
postcss "${FILES[@]}" --verbose --use autoprefixer -d resources
