server {
    listen 80 default_server;
    listen [::]:80 default_server;
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;

    ssl_certificate     /etc/ssl/certs/green-origin.pem;
    ssl_certificate_key /etc/ssl/private/green-origin.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size 100M;

    location /static/ { alias /root/green-oj/static/; }
    location /media/  { alias /mnt/cdn/media/; }

    location @icons {
        root /root/green-oj/resources/icons;
        log_not_found off;
        error_page 403 = @uwsgi;
        error_page 404 = @uwsgi;
    }
    location @uwsgi {
        uwsgi_pass unix:///tmp/green.sock;
        include uwsgi_params;
        uwsgi_param SERVER_SOFTWARE nginx/$nginx_version;
    }
    location / { try_files $uri @icons; }
}
