# Generated by Django 5.2.16 on 2026-07-20 02:16

import judge.models.problem
import judge.utils.problem_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0261_alter_problem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='format_name',
            field=models.CharField(choices=[('amoj', 'AMOJ'), ('atcoder', 'AtCoder'), ('default', 'Default'), ('ecoo', 'ECOO'), ('icpc', 'ICPC'), ('ioi', 'IOI'), ('ioi16', 'New IOI'), ('ultimate', 'Ultimate'), ('vnoj', 'VNOJ')], default='default', help_text='The contest format module to use.', max_length=32, verbose_name='contest format'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='pdf_description',
            field=models.FileField(blank=True, null=True, storage=judge.utils.problem_data.ProblemDataStorage(), upload_to=judge.models.problem.problem_directory_file, verbose_name='pdf statement'),
        ),
    ]
