# Generated by Django 5.2.16 on 2026-07-22 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0263_alter_problem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='code',
            field=models.SlugField(help_text='A short, unique code for the quiz, used in the URL after /quiz/', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', 'Quiz code must be ^[a-z0-9_]+$')], verbose_name='quiz code'),
        ),
    ]
