# Generated by Django 5.2.16 on 2026-07-22 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0264_alter_quiz_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='key',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', 'Contest id must be ^[a-z0-9_]+$')], verbose_name='contest id'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(help_text='Course name shown in URL', max_length=128, unique=True, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$', 'Only alphanumeric, hyphens and underscores')], verbose_name='course slug'),
        ),
    ]
