# Generated by Django 5.2.16 on 2026-08-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0271_merge_strict_and_hnoj'),
        ('judge', '0272_fill_blank_grading_strategies'),
    ]

    operations = [
    ]
