[program:green-bridged]
command=/root/green-oj/.venv/bin/python manage.py runbridged
directory=/root/green-oj
stopsignal=INT
autostart=true
autorestart=true
stdout_logfile=/var/log/green-bridged.out.log
stderr_logfile=/var/log/green-bridged.err.log
