[program:green-site]
command=/usr/bin/uwsgi --ini /etc/uwsgi/apps-available/green.ini
directory=/root/green-oj
stopsignal=QUIT
autostart=true
autorestart=true
stdout_logfile=/var/log/green-site.out.log
stderr_logfile=/var/log/green-site.err.log
