[program:green-celery]
command=/root/green-oj/.venv/bin/celery -A dmoj_celery worker
directory=/root/green-oj
autostart=true
autorestart=true
stdout_logfile=/var/log/green-celery.out.log
stderr_logfile=/var/log/green-celery.err.log
