#!/usr/bin/env python3
"""Regenerate the self-hosted Google Fonts in this directory.

Fetches each stylesheet in SOURCES from fonts.googleapis.com with a current
Chrome user agent (older agents get woff/ttf instead of woff2), downloads every
font file it references, and writes fonts.css with the src URLs repointed at
local files. The @font-face blocks are otherwise Google's own, verbatim —
unicode-range included, so a browser still fetches only the subsets a page
actually needs.

Run from this directory:

    python3 generate.py

Adding a family means adding its css2 URL to SOURCES and re-running. Stale
files are not pruned automatically; check `git status` afterwards.
"""

import os
import re
import shutil
import tempfile
import urllib.request

SOURCES = [
    "https://fonts.googleapis.com/css2?family=Fira+Code&family=Noto+Sans&display=swap",
    "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&display=swap",
    "https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap",
    "https://fonts.googleapis.com/css2"
    "?family=Inter:wght@100..900"
    "&family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap",
]

# Google serves woff2 only to agents it believes support it.
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36"
)

HEADER = """/*
 * Self-hosted Google Fonts: Fira Code, Noto Sans, Inter, Roboto, Roboto Mono.
 *
 * Generated by generate.py in this directory -- do not hand-edit. The
 * @font-face blocks are Google's own, verbatim, except that each src points at
 * a file here instead of fonts.gstatic.com. unicode-range is preserved, so the
 * browser still downloads only the subsets a page needs.
 */
"""

BLOCK = re.compile(r"(/\*[^*]*\*/\s*)?(@font-face\s*\{[^}]*\})", re.S)

# Faces that do not come from fonts.googleapis.com and so cannot be refetched by
# the loop below. Appended verbatim; the file each names lives in this directory
# and is committed alongside. Jersey M54 is used for the rank column on the user
# ranking pages and was loaded from fonts.cdnfonts.com over plain http.
NON_GOOGLE = """
/* jersey-m54 -- vendored from fonts.cdnfonts.com/s/2139 */
@font-face {
  font-family: 'Jersey M54';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: local('Jersey M54'), url(jersey-m54-normal-400.woff) format('woff');
}
"""


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request) as response:
        return response.read()


def slug(text):
    return re.sub(r"[^a-z0-9]+", "-", text.strip().lower()).strip("-")


def field(block, name):
    match = re.search(rf"{name}:\s*([^;]+);", block)
    return match.group(1).strip().strip("'\"") if match else ""


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    staging = tempfile.mkdtemp(prefix="gfonts-")

    url_to_local = {}
    taken = set()
    seen = set()
    blocks = []

    for source in SOURCES:
        css = fetch(source).decode("utf-8")
        for comment, block in BLOCK.findall(css):
            subset = slug(comment.strip("/*/ ").strip()) if comment else "misc"
            found = re.search(r"url\((https://[^)]+)\)", block)
            if not found:
                continue
            url = found.group(1)

            if url not in url_to_local:
                base = "{}-{}-{}-{}".format(
                    slug(field(block, "font-family")),
                    subset,
                    field(block, "font-style") or "normal",
                    slug(field(block, "font-weight") or "400"),
                )
                name, n = base + ".woff2", 1
                while name in taken:  # distinct files, same descriptors
                    n += 1
                    name = "{}-{}.woff2".format(base, n)
                taken.add(name)
                url_to_local[url] = name
                with open(os.path.join(staging, name), "wb") as out:
                    out.write(fetch(url))

            local = block.replace(url, url_to_local[url])
            key = re.sub(r"\s+", " ", local)
            if key in seen:
                continue
            seen.add(key)
            blocks.append("/* {} */\n{}".format(subset, local))

    for name in url_to_local.values():
        shutil.move(os.path.join(staging, name), os.path.join(here, name))
    with open(os.path.join(here, "fonts.css"), "w", encoding="utf-8") as out:
        out.write(HEADER + "\n" + "\n\n".join(blocks) + "\n" + NON_GOOGLE)
    shutil.rmtree(staging, ignore_errors=True)

    print("{} font files, {} @font-face blocks".format(len(url_to_local), len(blocks)))


if __name__ == "__main__":
    main()
